import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend, Julee, Cinzel_Decorative } from "next/font/google";
import "./globals.css";
import Navbar from '../components/ui/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const julee = Julee({
  variable: "--font-julee",
  subsets: ["latin"],
  weight: ["400"],
});

const cinzelDecorative = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

const navLinks = [
  {text:'OVERTURE', url:'#overture'},
  {text:'REPERTOIRE', url:'#repertoire'},
  {text:'CONCERT', url:'#concert'},
  {text:'ENCORE', url:'#encore'},
];

export const metadata: Metadata = {
  title: "Personal Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzelDecorative.variable} ${julee.variable} ${lexend.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar links={navLinks}/>
        <main>{children}</main>
      </body>
    </html>
  );
}