import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

  const lexend = Lexend({
    variable: "--font-lexend",
    subsets: ["latin"],
  });

const navLinks = [
  {text:'Home', url:'#home'},
  {text:'Services', url:'#services'},
  {text:'Projects', url:'#projects'},
  {text:'Contact', url:'#contact'},
];

export const metadata: Metadata = {
  title: "Personal Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar links={navLinks}/>
        <main>{children}</main>
      </body>
    </html>
  );
}